### ISSUE TITLE
confusion about the distance criteria of difficulty

### ISSUE THREAD

**Issue by Oshikaka** [naotoo1/Beyond-Neural-Scaling#35]
Hi there,

Thanks for the amazing work. I have some confusion with the distance that you define difficulty.

In your paper, you said under Chapter 6:

> we perform k-means clustering in the embedding space of an ImageNet pre-trained self-supervised model (here: SWaV [36]), and define the difficulty of each data point by the **cosine distance** to its nearest cluster centroid, or prototype.

So you use **cosine distance** to define difficulty in your paper.

However, in the code you provide, for example:

```
def ssl_kmeans(self, init='k-means++', n_init='auto'):
...
          self_supervised_learning_model = KMeans(
              n_clusters=number_of_clusters,
              random_state=self.random_state,
              init=init,
              n_init=n_init
          )
          self_supervised_learning_model.fit(embedded_space)
  
          prototype_responsibilities = self_supervised_learning_model.fit_transform(
              embedded_space
          )
```
The `prototype_responsibilities` is calculated based on **Euclidean distance**.

Also for `distance_space`, it is calculated based on **Euclidean distance**.
```
def ssl_fcm(self):
            cntr, u_matrix, u_matrix_init, distance_space, \
            objective_function_history, num_inter_run, \
            fuzzy_partition_coefficient = fuzz.cmeans(
                data=np.array(embedded_space).transpose(),
                c=number_of_clusters,
                m=2,
                error=0.001,
                maxiter=1000,
                init=None,
                seed=self.random_state
            )
```

Could you explain more about the above differences?
Thanks!

**Comment by naotoo1** [comment]
Recall the transformation between Euclidean distance and cosine similarity, which establishes a monotonic relationship between these two measures, thereby preserving the order of rankings. The choice of similarity measure may depend on various factors, including technical considerations and other contextual aspects. For difficulty-related criteria, if the goal is to replicate the behavior described in the referenced paper, it is imperative to consistently use cosine distance.
