### ISSUE TITLE
How can I use this code for object detection?

### ISSUE THREAD

**Issue by GodOfSmallThings** [naotoo1/Beyond-Neural-Scaling#8]
I think this is really interesting work and I want to use this code for object detection tasks such as Yolo, but I couldn't find out how to adapt it for such purposes.

How can I use it for object detection tasks? 

Thank you.

**Comment by naotoo1** [comment]
Select the optimal prototype-based self supervised metric depending on the complexity of the training set and  learning task. Prune  accordingly to specified size  based on your  technical choice of ratio between the size of  hard and easy examples keep. Use the resulting pruned set for as the training set for the object detection task.

**Comment by naotoo1** [comment]
> I think this is really interesting work and I want to use this code for object detection tasks such as Yolo, but I couldn't find out how to adapt it for such purposes.
> 
> How can I use it for object detection tasks?
> 
> Thank you.

**Comment by GodOfSmallThings** [comment]
should I modify example.py to test object detection model? I am very confused on how to modify the model in order to use this code for object detection task!

thank you.

**Comment by naotoo1** [comment]
@GodOfSmallThings,
`example.py` demonstrates a simplified application to  Learning Vector Quantization (LVQ) classification models.  
For  object detection task, refer to `bns.py` and review `example1.py`. Additionally, check `dataprune.py` for further insights.
